class EChartGoalsScoredOptionsCreation:
    def cummulative_goals_scored_line_graph(self, source_data):
        option={"title": {"text": "Cummulative Goals Scored Over Time",
                          "left": "center"},
                "dataset": [{"dimensions": [{"name": "player_name", 
                                             "type": "ordinal"},
                                            {"name": "date" },
                                            {"name": "goals"}],
                             "source": source_data},
                             {"fromDatasetIndex": 0,
                              "transform": [{"type": "filter",
                                             "config": {"dimension": "player_name",
                                                        "value": "Lionel Messi"}}]},
                             {"fromDatasetIndex": 0,
                              "transform": [{"type": "filter",
                                             "config": {"dimension": "player_name",
                                                        "value": "Cristiano Ronaldo"}}]}],
                "tooltip": {"trigger": "axis"},
                "legend": {"top": 30,},
                "xAxis": {"name": "Date", 
                          "type": "time",
                          "nameLocation": "center",
                          "nameGap": 30},
                "yAxis": {"name": "Goals",
                          "nameLocation": "center",
                          "nameGap": 40,
                          "type": "value"},
                "series": [{"type": "line",
                            "name": "Lionel Messi",
                            "datasetIndex": 1,
                            "encode": {"x": "date", 
                                       "y": "goals"}},
                           {"type": "line",
                            "name": "Cristiano Ronaldo",
                            "datasetIndex": 2,
                            "encode": {"x": "date",
                                       "y": "goals"}}]}
        
        return option


    def goals_scored_per_year_bar_graph(self, source_data):
        option={"title": {"text": "Goals Scored Per Year",
                          "left": "center"},
                "dataset": [{"dimensions": [{"name": "player_name", 
                                             "type": "ordinal"},
                                            {"name": "date" },
                                            {"name": "goals"}],
                             "source": source_data},
                             {"fromDatasetIndex": 0,
                              "transform": [{"type": "filter",
                                             "config": {"dimension": "player_name",
                                                        "value": "Lionel Messi"}}]},
                             {"fromDatasetIndex": 0,
                              "transform": [{"type": "filter",
                                             "config": {"dimension": "player_name",
                                                        "value": "Cristiano Ronaldo"}}]}],
                "tooltip": {"trigger": "axis"},
                "legend": {"top": 30,},
                "xAxis": {"name": "Year", 
                          "type": "time",
                          "nameLocation": "center",
                          "nameGap": 30},
                "yAxis": {"name": "Goals",
                          "nameLocation": "center",
                          "nameGap": 40,
                          "type": "value"},
                "series": [{"type": "bar",
                            "name": "Lionel Messi",
                            "datasetIndex": 1,
                            "encode": {"x": "date", 
                                       "y": "goals"}},
                           {"type": "bar",
                            "name": "Cristiano Ronaldo",
                            "datasetIndex": 2,
                            "encode": {"x": "date",
                                       "y": "goals"}}]}
        
        return option
    

    def goals_scored_per_competition_type_ratio(self, source_data):
        option={"title": {"text": "Goals Scored Per Game by Competition Type Ratio",
                          "left": "center"},
                "dataset": [{"dimensions": [{"name": "player_name", 
                                             "type": "ordinal"},
                                            {"name": "competition_type" },
                                            {"name": "goal_per_game_ratio"}],
                             "source": source_data},
                             {"fromDatasetIndex": 0,
                              "transform": [{"type": "filter",
                                             "config": {"dimension": "player_name",
                                                        "value": "Lionel Messi"}}]},
                             {"fromDatasetIndex": 0,
                              "transform": [{"type": "filter",
                                             "config": {"dimension": "player_name",
                                                        "value": "Cristiano Ronaldo"}}]}],
                "tooltip": {"trigger": "axis"},
                "legend": {"top": 30,},
                "xAxis": {"name": "Competition Type", 
                          "type": "category",
                          "nameLocation": "center",
                          "axisLabel": {"interval": 0,
                                        "rotate": 25},
                          "nameGap": 70},
                "yAxis": {"name": "Ratio",
                          "nameLocation": "center",
                          "nameGap": 40,
                          "type": "value"},
                "series": [{"type": "bar",
                            "name": "Lionel Messi",
                            "datasetIndex": 1,
                            "encode": {"x": "competition_type", 
                                       "y": "goal_per_game_ratio"}},
                           {"type": "bar",
                            "name": "Cristiano Ronaldo",
                            "datasetIndex": 2,
                            "encode": {"x": "competition_type",
                                       "y": "goal_per_game_ratio"}}]}
        
        return option


    def goals_scored_per_competition_type_sum(self, source_data):
        option={"title": {"text": "Goals Scored Per Game by Competition Type",
                          "left": "center"},
                "dataset": [{"dimensions": [{"name": "player_name", 
                                             "type": "ordinal"},
                                            {"name": "competition_type" },
                                            {"name": "goal_count"}],
                             "source": source_data},
                             {"fromDatasetIndex": 0,
                              "transform": [{"type": "filter",
                                             "config": {"dimension": "player_name",
                                                        "value": "Lionel Messi"}}]},
                             {"fromDatasetIndex": 0,
                              "transform": [{"type": "filter",
                                             "config": {"dimension": "player_name",
                                                        "value": "Cristiano Ronaldo"}}]}],
                "tooltip": {"trigger": "axis"},
                "legend": {"top": 30,},
                "xAxis": {"name": "Competition Type", 
                          "type": "category",
                          "nameLocation": "center",
                          "axisLabel": {"interval": 0,
                                        "rotate": 25},
                          "nameGap": 70},
                "yAxis": {"name": "Goals",
                          "nameLocation": "center",
                          "nameGap": 40,
                          "type": "value"},
                "series": [{"type": "bar",
                            "name": "Lionel Messi",
                            "datasetIndex": 1,
                            "encode": {"x": "competition_type", 
                                       "y": "goal_count"}},
                           {"type": "bar",
                            "name": "Cristiano Ronaldo",
                            "datasetIndex": 2,
                            "encode": {"x": "competition_type",
                                       "y": "goal_count"}}]}
        
        return option


    def goals_scored_and_match_outcome_heatmap(self, player, series_data, x_axis_data, y_axis_data, min_value, max_value):
        option={"title": {"text": f"{player} Goals Scored and Result",
                          "left": "center"},
                "tooltip": {"trigger": "item"},
                "visualMap": {"min": min_value,
                              "max": max_value,
                              "calculable": True,
                              "orient": "vertical",
                              "left": "right",
                              "top": "middle",
                              "inRange": {"color": ["#FD665F", "#FFCE34", "#65B581"]},
                              "bottom": "5%"},
                "xAxis": {"name": "Date",
                          "type": "time",
                          "nameLocation": "center",
                          "data": x_axis_data,
                          "nameGap": 30},
                "yAxis": {"name": "Result",
                          "nameLocation": "center",
                          "nameGap": 40,
                          "data": y_axis_data, 
                          "type": "category"},
                "series": [{"type": "heatmap",
                            "data": series_data}]}
        
        return option


class EChartConsistencyOptionsCreation:
    def contribution_and_match_outcome_bar_and_line_chart(self, source_data):
        option={"title": {"text": "Player Contributions and Contribution Ratios Per Year",
                          "left": "center"},
                "tooltip": {"trigger": "axis",
                            "axisPointer": {"type": "cross"}},
                "dataset": [{"dimensions": [{"name": "player_name", 
                                             "type": "ordinal"},
                                            {"name": "date" },
                                            {"name": "total_contributions"},
                                            {"name": "contribution_ratio"}],
                             "source": source_data},
                             {"fromDatasetIndex": 0,
                              "transform": [{"type": "filter",
                                             "config": {"dimension": "player_name",
                                                        "value": "Lionel Messi"}}]},
                             {"fromDatasetIndex": 0,
                              "transform": [{"type": "filter",
                                             "config": {"dimension": "player_name",
                                                        "value": "Cristiano Ronaldo"}}]}],
                "legend": {"top": 30},
                "xAxis": [{"type": "time",
                           "name": "Date",
                           "nameGap": 30,
                           "nameLocation": "center",
                           "axisPointer": {"type": "shadow"}}],
                "yAxis": [{"type": "value",
                           "name": "Total Contributions",
                           "nameLocation": "center",
                           "nameGap": 40},
                           {"type": "value",
                            "name": "Rolling Contribution Ratio",
                            "nameLocation": "center",
                            "nameRotate": 270,
                            "nameGap": 40}],
                "series": [{"type": "bar",
                            "name": "Lionel Messi Contribution Count",
                            "datasetIndex": 1,
                            "encode": {"x": "date", 
                                       "y": 2}},
                           {"type": "line",
                            "name": "Lionel Messi Contribution Ratio",
                            "datasetIndex": 1,
                            "yAxisIndex": 1,
                            "encode": {"x": "date", 
                                       "y": 3}},
                           {"type": "bar",
                            "name": "Cristiano Ronaldo Contribution Count",
                            "datasetIndex": 2,
                            "encode": {"x": "date",
                                       "y": 2}},           
                           {"type": "line",
                            "yAxisIndex": 1,
                            "name": "Cristiano Ronaldo Contribution Ratio",
                            "datasetIndex": 2,
                            "encode": {"x": "date",
                                       "y": 3}}]}

        return option
    

    def minutes_played_per_year_area_chart(self, source_data):
        option={"title": {"text": "Minutes Played Per Year",
                          "left": "center"},
                "legend": {"top": 30},
                "dataset": [{"dimensions": [{"name": "player_name", 
                                             "type": "ordinal"},
                                            {"name": "date" },
                                            {"name": "minutes"}],
                             "source": source_data},
                             {"fromDatasetIndex": 0,
                              "transform": [{"type": "filter",
                                             "config": {"dimension": "player_name",
                                                        "value": "Lionel Messi"}}]},
                             {"fromDatasetIndex": 0,
                              "transform": [{"type": "filter",
                                             "config": {"dimension": "player_name",
                                                        "value": "Cristiano Ronaldo"}}]}],
                "tooltip": {"trigger": "axis",
                            "axisPointer": {"type": "cross",
                                            "label": {"backgroundColor": "#6a7985"}}},
                "xAxis": {"name": "Date", 
                          "type": "time",
                          "nameLocation": "center",
                          "axisLabel": {"interval": 0},
                          "nameGap": 30},
                "yAxis": {"name": "Minutes",
                          "nameLocation": "center",
                          "nameGap": 40,
                          "type": "value"},
                "series": [{"type": "bar",
                            "name": "Lionel Messi",
                            "datasetIndex": 1,
                            "encode": {"x": "date", 
                                       "y": "minutes"}},

                           {"type": "bar",
                            "name": "Cristiano Ronaldo",
                            "datasetIndex": 2,
                            "encode": {"x": "date",
                                       "y": "minutes"}}]}

        return option
    

    def game_availability_per_year_bar_chart(self, source_data):
        option={"title": {"text": "Percentage of Game Played Per Year",
                          "left": "center"},
                "legend": {"top": 30},
                "dataset": [{"dimensions": [{"name": "player_name", 
                                             "type": "ordinal"},
                                            {"name": "date" },
                                            {"name": "Ratio"}],
                             "source": source_data},
                             {"fromDatasetIndex": 0,
                              "transform": [{"type": "filter",
                                             "config": {"dimension": "player_name",
                                                        "value": "Lionel Messi"}}]},
                             {"fromDatasetIndex": 0,
                              "transform": [{"type": "filter",
                                             "config": {"dimension": "player_name",
                                                        "value": "Cristiano Ronaldo"}}]}],
                "tooltip": {"trigger": "axis",
                            "axisPointer": {"type": "cross",
                                            "label": {"backgroundColor": "#6a7985"}}},
                "xAxis": {"name": "Date", 
                          "type": "time",
                          "nameLocation": "center",
                          "axisLabel": {"interval": 0},
                          "nameGap": 30},
                "yAxis": {"name": "Ratio",
                          "nameLocation": "center",
                          "nameGap": 40,

                          "axisLabel": {"formatter": "{value} %"},

                          "type": "value"},
                "series": [{"type": "bar",
                            "name": "Lionel Messi",
                            "datasetIndex": 1,
                            "encode": {"x": "date", 
                                       "y": "Ratio"}},

                           {"type": "bar",
                            "name": "Cristiano Ronaldo",
                            "datasetIndex": 2,
                            "encode": {"x": "date",
                                       "y": "Ratio"}}]}

        return option
