class EChartGoalsScoredOptionCreation:
    def cummulative_goals_scored_line_graph(self, source_data):
        option={"title": {"text": "Cummulative Goals Scored Over Time",
                          "left": "center"},
                "dataset": [{"dimensions": [{"name": "player_name", 
                                             "type": "ordinal"},
                                            {"name": "date" },
                                            {"name": "goals"}],
                             "source": source_data},
                             {"fromDatasetIndex": 0,
                              "transform": [{"type": "filter",
                                             "config": {"dimension": "player_name",
                                                        "value": "Lionel Messi"}}]},
                             {"fromDatasetIndex": 0,
                              "transform": [{"type": "filter",
                                             "config": {"dimension": "player_name",
                                                        "value": "Cristiano Ronaldo"}}]}],
                "tooltip": {"trigger": "axis"},
                "legend": {"top": 30,},
                "grid": {"containLabel": True,
                         "top": 60},
                "xAxis": {"name": "Date", 
                          "type": "time",
                          "nameLocation": "center",
                          "nameGap": 30},
                "yAxis": {"name": "Goals",
                          "nameLocation": "center",
                          "nameGap": 40,
                          "type": "value"},
                "series": [{"type": "line",
                            "name": "Lionel Messi",
                            "datasetIndex": 1,
                            "encode": {"x": "date", 
                                       "y": "goals"}},
                           {"type": "line",
                            "name": "Cristiano Ronaldo",
                            "datasetIndex": 2,
                            "encode": {"x": "date",
                                       "y": "goals"}}]}
        
        return option


    def goals_scored_per_year_bar_graph(self, source_data):
        option={"title": {"text": "Goals Scored Per Year",
                          "left": "center"},
                "dataset": [{"dimensions": [{"name": "player_name", 
                                             "type": "ordinal"},
                                            {"name": "date" },
                                            {"name": "goals"}],
                             "source": source_data},
                             {"fromDatasetIndex": 0,
                              "transform": [{"type": "filter",
                                             "config": {"dimension": "player_name",
                                                        "value": "Lionel Messi"}}]},
                             {"fromDatasetIndex": 0,
                              "transform": [{"type": "filter",
                                             "config": {"dimension": "player_name",
                                                        "value": "Cristiano Ronaldo"}}]}],
                "tooltip": {"trigger": "axis"},
                "legend": {"top": 30,},
                "grid": {"containLabel": True,
                         "top": 60},
                "xAxis": {"name": "Year", 
                          "type": "time",
                          "nameLocation": "center",
                          "nameGap": 30},
                "yAxis": {"name": "Goals",
                          "nameLocation": "center",
                          "nameGap": 40,
                          "type": "value"},
                "series": [{"type": "bar",
                            "name": "Lionel Messi",
                            "datasetIndex": 1,
                            "encode": {"x": "date", 
                                       "y": "goals"}},
                           {"type": "bar",
                            "name": "Cristiano Ronaldo",
                            "datasetIndex": 2,
                            "encode": {"x": "date",
                                       "y": "goals"}}]}
        
        return option
    

    def goals_scored_and_match_outcome_heatmap(self, player, series_data, x_axis_data, y_axis_data, min_value, max_value):
        option={"title": {"text": f"{player} Goals Scored and Result",
                          "left": "center"},
                "tooltip": {"trigger": "item"},
                "grid": {"containLabel": True},
                "visualMap": {"min": min_value,
                              "max": max_value,
                              "calculable": True,
                              "orient": "vertical",
                              "left": "right",
                              "top": "middle",
                              "inRange": {"color": ["#FD665F", "#FFCE34", "#65B581"]},
                              "bottom": "5%"},
                "xAxis": {"name": "Date",
                          "type": "time",
                          "nameLocation": "center",
                          "data": x_axis_data,
                          "nameGap": 30},
                "yAxis": {"name": "Result",
                          "nameLocation": "center",
                          "nameGap": 40,
                          "data": y_axis_data, 
                          "type": "category"},
                "series": [{"type": "heatmap",
                            "data": series_data}]}
        
        return option
